var searchData=
[
  ['mgeofencelist',['mGeofenceList',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_place.html#a017075a8b5bba1c66d3f6cb1ae3b59cb',1,'com::mobstac::beaconstac::core::MSPlace']]],
  ['mgoogleapiclient',['mGoogleApiClient',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_place.html#ad533b66870a9d20bd25ae47fa4c9b7c2',1,'com::mobstac::beaconstac::core::MSPlace']]],
  ['min_5fbroadcast_5fdelay',['MIN_BROADCAST_DELAY',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_constants.html#a04ecddcc7963e30af3e320c913b90ca1',1,'com::mobstac::beaconstac::core::MSConstants']]],
  ['modelbase',['ModelBase',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_model_base.html',1,'com::mobstac::beaconstac::models']]],
  ['msaction',['MSAction',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_action.html',1,'com::mobstac::beaconstac::models']]],
  ['msactiontype',['MSActionType',['../enumcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_action_1_1_m_s_action_type.html',1,'com::mobstac::beaconstac::models::MSAction']]],
  ['msbeacon',['MSBeacon',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_beacon.html',1,'com::mobstac::beaconstac::models']]],
  ['msbeacon',['MSBeacon',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_beacon.html#ab78e233e40c2761ef540bc454cf41f3f',1,'com.mobstac.beaconstac.models.MSBeacon.MSBeacon(UUID uuid, int major, int minor)'],['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_beacon.html#ad211985a6e0fd6f720b79f075cabe31a',1,'com.mobstac.beaconstac.models.MSBeacon.MSBeacon(Parcel p)']]],
  ['msbeaconaffinity',['MSBeaconAffinity',['../enumcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_b_l_e_service_1_1_m_s_beacon_affinity.html',1,'com::mobstac::beaconstac::core::MSBLEService']]],
  ['msbeaconproximity',['MSBeaconProximity',['../enumcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_rule_processor_1_1_m_s_beacon_proximity.html',1,'com::mobstac::beaconstac::core::MSRuleProcessor']]],
  ['msbleservice',['MSBLEService',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_b_l_e_service.html',1,'com::mobstac::beaconstac::core']]],
  ['msbleservicebinder',['MSBLEServiceBinder',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_b_l_e_service_1_1_m_s_b_l_e_service_binder.html',1,'com::mobstac::beaconstac::core::MSBLEService']]],
  ['mscard',['MSCard',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_card.html',1,'com::mobstac::beaconstac::models']]],
  ['mscardtype',['MSCardType',['../enumcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_card_1_1_m_s_card_type.html',1,'com::mobstac::beaconstac::models::MSCard']]],
  ['msconstants',['MSConstants',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_constants.html',1,'com::mobstac::beaconstac::core']]],
  ['mscontentprovider',['MSContentProvider',['../classcom_1_1mobstac_1_1beaconstac_1_1provider_1_1_m_s_content_provider.html',1,'com::mobstac::beaconstac::provider']]],
  ['mseventtype',['MSEventType',['../enumcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_rule_processor_1_1_m_s_event_type.html',1,'com::mobstac::beaconstac::core::MSRuleProcessor']]],
  ['msexception',['MSException',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_exception.html',1,'com::mobstac::beaconstac::utils']]],
  ['msgeofenceerrormessages',['MSGeofenceErrorMessages',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_geofence_error_messages.html',1,'com::mobstac::beaconstac::utils']]],
  ['msjsonobjectrequest',['MSJsonObjectRequest',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_json_object_request.html',1,'com::mobstac::beaconstac::utils']]],
  ['mslogger',['MSLogger',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_logger.html',1,'com::mobstac::beaconstac::utils']]],
  ['msmedia',['MSMedia',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_media.html',1,'com::mobstac::beaconstac::models']]],
  ['msplace',['MSPlace',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_place.html#a769070e8ff0aba6d9409643addd88408',1,'com.mobstac.beaconstac.core.MSPlace.MSPlace(Context context)'],['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_place.html#a1966c88f6346afc4c664fffcde7e5ef7',1,'com.mobstac.beaconstac.core.MSPlace.MSPlace(Parcel p)']]],
  ['msplace',['MSPlace',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_place.html',1,'com::mobstac::beaconstac::core']]],
  ['msreachability',['MSReachability',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_reachability.html',1,'com::mobstac::beaconstac::utils']]],
  ['msrule',['MSRule',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_rule.html',1,'com::mobstac::beaconstac::models']]],
  ['msrulebeacon',['MSRuleBeacon',['../classcom_1_1mobstac_1_1beaconstac_1_1models_1_1_m_s_rule_beacon.html',1,'com::mobstac::beaconstac::models']]],
  ['msruleprocessor',['MSRuleProcessor',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_rule_processor.html',1,'com::mobstac::beaconstac::core']]],
  ['msruleprocessor',['MSRuleProcessor',['../classcom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_rule_processor.html#a516a0b9648d499c3d2acb746b6fd6406',1,'com::mobstac::beaconstac::core::MSRuleProcessor']]],
  ['msruleprocessorcallback',['MSRuleProcessorCallback',['../interfacecom_1_1mobstac_1_1beaconstac_1_1core_1_1_m_s_rule_processor_1_1_m_s_rule_processor_callback.html',1,'com::mobstac::beaconstac::core::MSRuleProcessor']]],
  ['msscanresult',['MSScanResult',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_scan_result.html',1,'com::mobstac::beaconstac::utils']]],
  ['mssharedpreference',['MSSharedPreference',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_shared_preference.html',1,'com::mobstac::beaconstac::utils']]],
  ['msvolleysingleton',['MSVolleySingleton',['../classcom_1_1mobstac_1_1beaconstac_1_1utils_1_1_m_s_volley_singleton.html',1,'com::mobstac::beaconstac::utils']]]
];
